spring:
  application:
    name: Sistema para gerenciamento de academia

  springdoc:
    api-docs:
      path: /v1/api-docs
    swagger-ui:
      path: /swagger-ui.html

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?ApplicationName=SistemaParaGerenciamentoDeAcademia
    username: postgres
    password: admin

  hikari:
    maximumPoolSize: 3
    minimumIdle: 2
    idleTimeout: 20000
    poolName: SistemaDeControleDeNotaspool

